services:
  - type: web
    name: multi-agent-rag-chatbot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: PYTHON_VERSION
        value: 3.11.0
